export const location = [
    'A F Station Yelahanka',
    'Achitnagar',
    'Adarangi',
    'Adugodi',
    'Agara',
    'Agram',
    'Air Force Hospital',
    'Ajjanahalli',
    'Alurduddanahalli',
    'Aluru',
    'Amruthahalli',
    'Anandnagar',
    'Anekal',
    'Anjanapura',
    'Anneshwara',
    'Antharahalli',
    'Arabic College',
    'Aradeshanahalli',
    'Arakere',
    'Arallumallige',
    'Arasinakunte',
    'Wilson Garden',
    'Wipro Limited',
    'Yadavanahalli',
    'Yelachenahalli',
    'Yelahanka',
    'Yelahanka Satellite Town',
    'Yelekyathanahalli',
    'Yeliyur',
    'Yennegere',
    'Yentiganahalli',
    'Yeshwanthpur Bazar',
    'Yeswanthpura',
    'Thippasandra',
    'Thyagarajnagar',
    'Tilaknagar',
    'Tippur',
    'Training Command IAF',
    'Tubugere',
    'Tyagrajnagar',
    'Tyamagondlu',
    'Udaypura',
    'Udukunte',
    'Uganavadi',
    'Ullalu Upanagar',
    'Vagata Agrahara',
    'Vanakanahalli',
    'Vartur',
    'Vasanthanagar',
    'Veerapura',
    'Venkatagirikote',
    'Venkateshapura',
    'Vidhana Soudha',
    'Vidyanagara',
    'Vidyaranyapura',
    'Vijayanagar East',
    'Vijayanagar',
    'Vijayapaura',
    'Vimanapura',
    'Virgonagar',
    'Vishwanathapura',
    'Viswaneedam',
    'Viveknagar',
    'Vyalikaval Extn',
    'West of Chord Road II stage',
    'Whiteﬁeld',
    'Sidihoskote',
    'Silvepura',
    'Singanayakanahalli',
    'Singasandra',
    'Sirigiripura',
    'Sivan Chetty Gardens',
    'Soladevanahalli',
    'Solur',
    'Somanhalli',
    'Sondekoppa',
    'Sri Chowdeshwari',
    'Sri Subramanyaghati',
    'Srirampuram',
    'St. John Medical College',
    'St. Thomas Town',
    'State Bank Of Mysore Colony',
    'Subramanyapura',
    'Sugganahalli',
    'Sulebele',
    'Sulikere',
    'Swimming Pool Extn',
    'Syakaladevanapura',
    'Tarabanahalli',
    'Tarahunise',
    'Taralu',
    'Tavarekere',
    'Tavarekere',
    'Tavarekere',
    'Teppadabeguru',
    'Thalaghattapura',
    'Thammanayakanahalli',
    'Thataguni',
    'Thattekuppe',
    'Ragihalli',
    'Rajaghatta',
    'Rajajinagar',
    'Rajajinagar IVth Block',
    'Rajanakunte',
    'Rajarajeshwarinagar',
    'Rajbhavan',
    'Ramamurthy Nagar',
    'Rameshnagar',
    'Rameshwara',
    'Ramohalli',
    'Reddihalli',
    'Richmond Town',
    'Rv Niketan',
    'Sadahalli',
    'Sadashivanagar',
    'Sahakaranagar P.O',
    'Sakalavara',
    'Sakkaaregollahalli',
    'Samandur',
    'Samethanahalli',
    'Sampangiramnagar',
    'Sankighatta',
    'Sarjapura',
    'Sasalu',
    'Science Institute',
    'Seshadripuram',
    'Shanthinagar',
    'Shivagange',
    'Shivakote',
    'Shivanapura',
    'Shivanapura',
    'Shivapura',
    'Mahalakshmipuram Layout',
    'Mahatma Gandhi Road',
    'Makali',
    'Mallarabanavadi',
    'Mallathahalli',
    'Mallathahalli',
    'Malleswaram',
    'Malleswaram West',
    'Mandibele',
    'Mandigere',
    'Manne',
    'Manniganahalli',
    'Maralakunte',
    'Marasandra',
    'Marathahalli Colony',
    'Marikuppe',
    'Marsur',
    'Maruthi Sevanagar',
    'Mathahalli',
    'Mathikere',
    'Mavalli',
    'Mayasandra',
    'Mayasandra',
    'Medimallasandra',
    'Melekote',
    'Mico Layout',
    'Motagondanahalli',
    'Mount St Joseph',
    'Msrit',
    'Mugabala',
    'Mullahalli',
    'Mundur',
    'Museum Road',
    'Muthanallur',
    'Muthusandra',
    'Mylanahalli',
    'Naduvathi',
    'NAGADENAHALLI',
    'Nagarbhavi',
    'Nagasandra',
    'NAL',
    'Nandagudi',
    'Nandinilayout',
    'Narasandra',
    'Narasipura',
    'Narayanapura',
    'Nayandahalli',
    'Nelakadiranahalli',
    'Nelamangala',
    'Nelavagilu',
    'Neralur',
    'Neriga',
    'New Thippasandra',
    'Niduvanda',
    'Obalapura',
    'P&T Col. Kavalbyrasandra',
    'Padmanabhnagar',
    'Palace Guttahalli',
    'Pampamahakavi Road',
    'Panathur',
    'Peenya Dasarahalli',
    'Peenya I Stage',
    'Peenya Small Industries',
    'Purushanahalli',
    'R T Nagar',
    'R.M.V. Extension II Stage',
    'Doddabele',
    'Doddagattiganabbe',
    'Doddagubbi',
    'Doddahejjaji',
    'Doddajala',
    'Doddakallasandra',
    'Doddamudigere',
    'Doddanallala',
    'Doddanekkundi',
    'Doddasanne',
    'Doddasomanahalli',
    'Doddatumkur',
    'Domlur',
    'Dommasandra',
    'Doorvaninagar',
    'Dr. Ambedkar Veedhi',
    'Dr. Shivarama Karanth Nagar',
    'Electronics City',
    'EPIP',
    'Fraser Town',
    'G.K.V.K.',
    'Gangonahalli',
    'Gantiganahalli',
    'Gaviopuram Extension',
    'Gayathrinagar',
    'Girinagar',
    'Gollahalli',
    'Gottigere',
    'Governmemnt Electric Factory',
    'Guddanahalli',
    'Gudemaranahalli',
    'Gundamgere',
    'Gunjur',
    'Bylakere',
    'Bylanarasapura',
    'C.V.Raman Nagar',
    'Carmelram',
    'Chamarajasagara',
    'Chamrajpet',
    'Chandapura',
    'Chandapura',
    'Chandra Lay Out',
    'Channarayapatna',
    'Chickpet',
    'Chikkabanavara',
    'Chikkabidarkal',
    'Chikkajala',
    'Chikkalasandra',
    'Chikkanahalli',
    'Chudenapura',
    'Chunchanakuppe',
    'CMM Court Complex',
    'CMP Centre And School',
    'CRPF Campus Yelahanka',
    'Dasanapura',
    'Dasarahalli(Srinagar)',
    'Deepanjalinagar',
    'Devanagundi',
    'Devanahalli',
    'Devarahosahalli',
    'Devasandra',
    'Dharmaram College',
    'Dobbespet',
    'Dodballapura Bazar',
    'Dodballapura',
    'Doddabelavangala',
    'Bangalore Sub Foreign Post',
    'Bannerghatta Road',
    'Bannerghatta',
    'Bapagrama',
    'Baragenahalli',
    'Basavanagudi',
    'Basaveshwaranagar',
    'Basettihalli',
    'Begur',
    'Begur',
    'Bellandur',
    'Bendiganahalli',
    'Benson Town',
    'Bestamaranahalli',
    'Bettahalsur',
    'Bettakote',
    'Bhattarahalli',
    'Bidalur',
    'Bidaraguppe',
    'Bidrahalli',
    'Bijjawara',
    'Billanakote',
    'Biskur',
    'Bnagalore Viswavidalaya',
    'Bolare',
    'Bommanahalli',
    'Bommasandra Industrial Estate',
    'BSF Campus Yelahanka',
    'Budigere',
    'Budihal',
    'Byagadadenahalli',
    'Byatarayanapura',
    'Byatha',
    'Bagalur',
    'Baginigere',
    'Baktharahalli',
    'Banashankari III Stage',
    'Banashankari',
    'Banaswadi',
    'Banavadi',
    'Bandikodigehalli',
    'Bangalore Bazaar',
    'Bangalore City',
    'Bangalore Corporation Building',
    'Bangalore Dist Ofﬁces Bldg',
    'Bangalore G.P.O.',
    'Bangalore International Airport'
];